### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by inorick** [grigorig/chachapoly#1]
Thank you for this compact implementation of RFC 7539. I was curious as to what the license of this project is. As poly1305-donna is [MIT licensed](https://github.com/floodyberry/poly1305-donna#license) I was hoping this code would be too.

**Comment by grigorig** [comment]
Yes, it's MIT. See the license headers.

**Comment by grigorig** [comment]
I added a section to the README to clarify.

**Comment by inorick** [comment]
Thanks. FYI, the Github way of adding a license is documented here:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository
